# Generated by Django 3.2.15 on 2025-04-16 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
        ('store', '0001_initial'),
        ('order', '0002_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('book', 'Book'), ('merchandise', 'Merchandise')], default='book', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='merchandise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchandise.product'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='carrier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.book'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('order placed', 'Order Placed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out for delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='order placed', max_length=20),
        ),
    ]
