# Generated by Django 3.2.15 on 2025-05-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20250507_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
    ]
